### ISSUE TITLE
Question -- defaultValue & Upsert

### ISSUE THREAD

**Issue by lucendio** [aldeed/meteor-simple-schema#454]
Hi,

I stumbled upon the case where I performed an upsert (essentially it was an insert, because the object did not exist) and it throw an error which says the field is required. Probably I also should mention that the upsert/insert code were running on the server and the selector was not the ``_id``.
I tested the same with an insert and everything worked fine. I also tried it with ``optional: true`` - same result, the field did not appear in the database. 
Is this behavior on purpose? I coundnt find anything about that in the docs.

```javascript
visibility: {
    type: String,
    label: 'visibility',
    allowedValues: [ 'str1', 'str2', 'str3' ],
    defaultValue: 'str1'
}
```

EDIT: ``defaultValue: 'srt1'`` --> ``defaultValue: 'str1'``

**Comment by gabrielpoca** [comment]
@lucendio your default value is not in the list of allowed values, can that be the issue or was it just a mistake when placing the code here?

**Comment by lucendio** [comment]
silly type in this example code. rechecked with the real code though. defaultValue and allowedValues[0] are definitely the same. so it is part of the list. but throws an erros as descibed above.

**Comment by lucendio** [comment]
maybe associated with [collection2 issues #253](https://github.com/aldeed/meteor-collection2/issues/253)?

**Comment by AndyHan1001** [comment]
I have updated to the latest version, but the issue is still here.

**Comment by aldeed** [comment]
Yeah this is fixed in devel branch, but I haven't released v2 yet.

**Comment by pcorey** [comment]
@aldeed I'm still experiencing this. Has your fix been released?

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
